[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # git
repo = 'tpope/vim-fugitive'

