[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # git
repo = 'tpope/vim-fugitive'

[[plugins]] # filer
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
let g:ale_fixers = {
\   'javascript': ['prettier', 'eslint'],
\   'css': ['prettier'],
\   'ruby': ['rubocop'],
\}
'''

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
let g:vue_pre_processors = []
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
let g:EditorConfig_exclude_patterns = ['fugitive://.\*']
'''
